name: Deploy EC2 with Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check AWS S3 Access
        run: aws s3 ls    

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./terraform
        
      - name: Apply Terraform
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Checking state file
        run: terraform state list
        working-directory: ./terraform

      - name: Fetching Public IP of EC2 Instance
        id: get_ip
        run: echo "EC2_HOST=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
        working-directory: ./terraform

  deploy:
    needs: terraform  # This job runs AFTER Terraform completes
    runs-on: ubuntu-latest

    steps:
      - name: Wait for EC2 to be ready
        run: sleep 60  # Give instance some time to become accessible

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}  # Use the extracted public IP
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
