name: Deploy EC2 and Angular App

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Create EC2 Instance with Terraform
    runs-on: ubuntu-latest

    outputs:  # ✅ Define outputs for the job
      PUBLIC_IP: ${{ steps.get-ip.outputs.PUBLIC_IP }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get EC2 Public IP
        id: get-ip
        run: |
          echo "Fetching EC2 Public IP..."
          PUBLIC_IP=$(terraform output -raw instance_public_ip | awk 'NR==1 {print $1}')
          if [[ -z "$PUBLIC_IP" ]]; then
            echo "Error: EC2 Public IP is empty!" >&2
            exit 1
          fi
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "PUBLIC_IP=$PUBLIC_IP" >> "$GITHUB_OUTPUT"
          echo "EC2 Public IP: $PUBLIC_IP"
        working-directory: ./terraform

  deploy:
    name: Deploy Angular App to EC2
    runs-on: ubuntu-latest
    needs: terraform  # ✅ Ensure Terraform job completes before this job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 Host to Known Hosts
        run: |
          PUBLIC_IP="${{ needs.terraform.outputs.PUBLIC_IP }}"
          echo "EC2 Public IP: $PUBLIC_IP"
          if [[ -z "$PUBLIC_IP" ]]; then
            echo "Error: PUBLIC_IP is empty!" >&2
            exit 1
          fi
          ssh-keyscan -H "$PUBLIC_IP" >> ~/.ssh/known_hosts

      - name: Install Docker & Deploy Angular App
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ needs.terraform.outputs.PUBLIC_IP }} << 'EOF'
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

          # Pull latest Angular Docker image
          docker pull your-dockerhub-username/angular-app:latest

          # Run container on port 8080
          docker run -d -p 8080:80 --name angular-app your-dockerhub-username/angular-app:latest
          EOF

      - name: Confirm Deployment
        run: echo "Application deployed at http://${{ needs.terraform.outputs.PUBLIC_IP }}:8080"
